spring.application.name=ServiceMonitoringSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/monitoringdb
spring.datasource.username=postgres
spring.datasource.password=1308
spring.jpa.hibernate.ddl-auto=update
server.port=8081