# Application name
spring.application.name=MonitoringSystem

# PostgreSQL database connection
spring.datasource.url=jdbc:postgresql://dpg-abc123.oregon-postgres.render.com/service_monitoring_db
spring.datasource.username=service_monitoring_db_user
spring.datasource.password=jZTp402dRTQmWoRIKAArSzY2M0B5uZFL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahitha2005.mahi@gmail.com
spring.mail.password=unplszkcutkkahsp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Render dynamic port
server.port=${PORT:8080}