spring.application.name=MonitoringSystem

# ===========================
# DATABASE CONFIG (RENDER)
# ===========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / HIBERNATE CONFIG
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# MAIL CONFIG
# ===========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahitha2005.mahi@gmail.com
spring.mail.password=unplszkcutkkahsp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===========================
# SERVER PORT (RENDER)
# ===========================
server.port=${PORT:8080}